version: "3"

services:
  chatgpt-discord-bot:
    build: .
    image: chatgpt-discord-bot
    container_name: chatgpt-discord-bot
    volumes:
      - ./.env:/applebaum-projects-07-discord-chatgpt/.env