name: 'deploy-app'
description: 'Builds Docker image, pushes to register, then deploys image into container on remote server when '

on:
  push:
    branches:
      -main

jobs:
  build-deploy-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate .env file
        run:
          echo DISCORD_TOKEN="${{ secrets.DISCORD_TOKEN }}" >> .env
          echo OPENAI_KEY="${{ secrets.OPENAI_KEY }}" >> .env
          echo REPLY_ALL_CHANNEL_ID="${{ vari" >> .env
          echo ENGINE="gpt-3.5-turbo" >> .env
          echo REPLYING_ALL="FALSE" >> .env

      - name: Build Docker image
        run:
          docker build . --file Dockerfile --tag prod:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker image
        run:
          docker tag prod:latest ruuffian/prod:latest

      - name: Push image to Docker Hub
        run: docker push ruuffian/prod:latest

      - name: SSH into Digital Ocean VM
        run:
          ssh ${{ secrets.DO_USER }}@${{ secrets.DO_IP }}

      - name: Tear down old container
        run:



