# Builds Docker image, pushes to register, then deploys image into container on remote server when main branch has changes

name: Deploy App

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate .env file
        run:
          echo DISCORD_TOKEN="${{ secrets.DISCORD_TOKEN }}" > .env
          echo OPENAI_KEY="${{ secrets.OPENAI_KEY }}" >> .env
          echo DISCORD_CHANNEL_ID="${{ env.CHANNEL_ID }}" >> .env
          echo REPLY_ALL_CHANNEL_ID="${{ env.REPLY_CHANNEL_ID }}" >> .env
          echo ENGINE="gpt-3.5-turbo" >> .env
          echo LOGGING="True" >> .env

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/chatdd:latest

      - name: SSH into Digital Ocean VM
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DO_IP }}
          username: ${{ secrets.DO_USER }}
          password: ${{ secrets.DO_SSH_KEY }}
          script: |
            docker-compose down
            docker-compose pull
            docker-compose up -d



